<a href="https://colab.research.google.com/github/rasaltejas/MATH_for_ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#creating numpy / n-d array
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [7]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr6=np.arange(5,15,2)
arr6

array([ 5,  7,  9, 11, 13])

In [17]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [18]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

#Properties & attributes
1.   shape
2.   nDim
3.   size
4.   itemsize
5.   Dtype
6.  astype()





In [21]:
arr1=np.array([1,2,3,4,5])
arr1.shape

(5,)

In [22]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2.shape

(2, 3)

In [30]:
arr9=np.array([[[1,2],[4,5]], [[1,2],[4,5]]])
arr9

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [31]:
arr9.shape

(2, 2, 2)

In [28]:
arr9.ndim

3

In [39]:
arr1.size

5

In [48]:
arr1.itemsize

8

In [47]:
arr9=np.array([[[1,2],[4,5]], [[1,2],[4,5]]])
arr9.itemsize

8

In [46]:
arr8.dtype

dtype('float64')

In [45]:
arr9.dtype

dtype('int64')

In [49]:
#float colsume lots of data by using this we convert data in to int
arr9.astype('float')

array([[[1., 2.],
        [4., 5.]],

       [[1., 2.],
        [4., 5.]]])

#List Vs Array
1.    Faster
2.   convenient
3.   less memory



In [56]:
#lets prove less memoey
lista=range(100)
arr11=np.arange(100)

In [57]:
import sys

In [58]:
print(sys.getsizeof(87)*len(lista))

2800


In [59]:
print(arr11.itemsize*arr11.size)

800


In [60]:
#lets prove fast
import time

In [ ]:
x = range(100000)
y=range(100000,200000)
